name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: configure
    
    - name: Build and Deploy
      run: |
         sudo apt-get update -y
         sudo apt-get install -y subversion g++ zlib1g-dev build-essential git python python3 python3-distutils libncurses5-dev gawk gettext unzip file libssl-dev wget libelf-dev ecj fastjar java-propose-classpath
         
    - name: Update feeds
      run: |
          sed -i 's/\"#src-git\"/\"src-git\"/g' ./feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
    - name: Generate configuration file
      run: |
       make menuconfig
    
    - name: Build  firmware
      run: |
       make 
    
    - name: Prepare artifact
      run: |
         find ./bin/targets/ -type d -name "packages" | xargs rm -rf {}

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
            name: OpenWrt_firmware
            path: ./bin/targets/
